-- 코드를 입력하세요
# CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY
SELECT crcc.car_id as CAR_ID
FROM CAR_RENTAL_COMPANY_CAR crcc
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh ON crcc.CAR_ID = crcrh.CAR_ID
WHERE crcc.CAR_TYPE LIKE '세단' AND Month(crcrh.START_DATE) = '10'
GROUP BY crcc.car_id
ORDER BY crcc.car_id desc